"""PBT — round-trip property: any UUID generated by the in-house generator
must validate as a UUIDv7 by the in-house validator.

Why round-trip and not monotonicity:
  src/python/transactionify/tools/generators/uuid.py falls back to uuid4
  when uuid_utils is not installed (and it is not in the fork's deps).
  A monotonicity property would falsify on the fallback path; round-trip
  tests the generator/validator contract directly and is robust.

Bounded scope: ONE Hypothesis test, < 30 lines. Not a sweep.
"""
import pytest
from hypothesis import given, settings, strategies as st

from src.python.transactionify.tools.generators.uuid import generate_uuidv7
from src.python.transactionify.tools.validators.uuid import is_valid_uuidv7


@pytest.mark.pbt
@given(st.integers(min_value=1, max_value=50))
@settings(max_examples=25, deadline=None)
def test_generate_uuidv7_round_trips_through_validator(_n: int):
    """Property: every UUID we generate validates as UUIDv7 by our own validator.

    The Hypothesis strategy is a simple int (the function takes no args); we
    use @given to make the test repeat across draws and to surface in the
    --hypothesis-show-statistics output, satisfying the 'PBT actually ran'
    invariant from GP-009a's gherkin.
    """
    uid = generate_uuidv7()
    assert is_valid_uuidv7(uid), f"generated {uid!r} did not validate as UUIDv7"
